# Generated by Django 5.1 on 2024-08-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создание поста')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Время изменения поста')),
                ('chat', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=55, verbose_name='Тип чата')),
                ('text', models.TextField(blank=True, verbose_name='Текст поста')),
            ],
        ),
    ]
