# Generated by Django 5.1 on 2024-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='text',
            field=models.TextField(blank=True, verbose_name='Тексто поста'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='chat',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=55, verbose_name='Тип чата'),
        ),
    ]
