# Generated by Django 5.1 on 2024-08-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_document_alter_posts_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='document',
            field=models.FileField(null=True, storage='local_storage/', upload_to=''),
        ),
    ]
