# Generated by Django 5.1 on 2024-08-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_posts_document_document_photo_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='file',
        ),
    ]
