# Generated by Django 5.1 on 2024-08-21 11:17

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_posts_document_alter_posts_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='document',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
    ]
