
version: '3.9'

services:

  postgres:
    image: postgres:alpine
    container_name: postgres_pser
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
    ports:
      - "${db_port}:5432"
    networks:
      - service


  django:
    build: .
    container_name: django_app_pser
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=PostsService.settings
      - POSTGRES_DB=${db_name}
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_HOST=${db_host}
      - POSTGRES_PORT=${db_port}
    depends_on:
      - postgres
    networks:
      - service
  


  minio:
    image: minio/minio:latest
    container_name: minio_pser2
    command: server /data --console-address ":9090"
    env_file:
      - .env
    ports:
      - 9000:9000
      - 9090:9090



networks:
  service:
    driver: bridge