# Generated by Django 5.1 on 2024-11-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='update_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
