version: '3.9'

services:

  postgres:
    image: postgres:alpine
    container_name: postgres_p
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
    ports:
      - "${db_port}:5432"
    networks:
      - postservice


networks:
  postservice:
    driver: bridge