# Generated by Django 5.1 on 2024-10-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JWT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
